language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - #test
  - sudo add-apt-repository ppa:nixnote/nixnote2-stable -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install git-core qt5-default build-essential wget curl make pkg-config libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev libcurl4-openssl-dev libpoppler-qt5-dev libqt5webkit5-dev qt5-qmake qttools5-dev-tools tidy-html56
  - #source /opt/qt*/bin/qt*-env.sh

script:
  - qmake CONFIG+=release PREFIX=appdir/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir/usr -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x qtsandbox-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh qtsandbox*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
